### ISSUE TITLE
First popover incorrectly highlighted on hover

### ISSUE THREAD

**Issue by schang933** [milligram/milligram.github.io#19] opened 2016-10-29 17:41 UTC
### Steps to reproduce

Click a popover element in the nav bar on the [main site](https://milligram.github.io) and hover over the first link. The ^ triangle used to be purple in previous versions, but is now white. I imagine this is a bug.

This exists in Safari 9 on OS X 10.11 and Chromium 52 on Windows 10.

![milligram popover](https://cloud.githubusercontent.com/assets/18754552/19831646/e6a666fc-9dd4-11e6-9ae3-fb33a49062aa.png)

**Comment by cjpatoilo** [comment] 2016-11-11 14:18
Hi @schang933 It's okay, this is not a bug. I changed that behavior. Let me know if you need anything. For now, I will close this issue.

Thanks for the attention.

**Closed by cjpatoilo** 2016-11-11 14:18 UTC
